# Generated by Django 5.2.6 on 2025-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_DB',
            fields=[
                ('car_Brand', models.CharField(max_length=10)),
                ('Number_plate', models.CharField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('color', models.CharField()),
                ('warranty', models.IntegerField()),
            ],
        ),
    ]
